import { uid, createParam } from './helpers'

function p(desc) { return createParam(desc) }

function relayParams(prefix) {
  return [
    p('Make'), p('Model number'), p('Current rating'),
    p('Auxiliary supply — AC / DC-24V / DC-110V / DC-220V'),
    p('Type of communication port — RS485 / MODBUS TCP-IP / OFC / IEC 61850'),
    p('Check model & serial number: display vs barcode label'),
    p('Check required inputs uploaded in relay as per design / technical details'),
    p('Check each protection enabled as per trip logic scheme / IEC curve'),
    p('Functional test of each fault as per trip logic scheme'),
    p('Check assigned output including spare is functioning in relay'),
    p('Measure milliamps output for KW in relay after injecting voltage & current'),
    p('Check digital input logic as per trip logic scheme'),
    p('Check LED assigned as per trip logic scheme'),
    p('Check ANSI code pasted on each LED in relay'),
    p('Review PDF extracted file from relay after each parameter is enabled'),
    p('Check relay body earthing connected to instrument earthing'),
  ]
}

export function buildDefaultSections() {
  return [
    { id: uid(), title: 'Bill of Material Check', enabled: true, params: [p('Bill of Material as per approved Drawing')] },
    { id: uid(), title: 'Dimensional Checks', enabled: true, params: [
      p('Panel overall dimension (L x H x B)'), p('Panel sheet thickness'), p('Paint shade'),
      p('Paint thickness (DFT measurement)'), p('Instrument earth bus bar material — Copper / Aluminium'),
      p('Power earth bus bar material — Copper / Aluminium'), p('Earth bus bar size — Specified & Actual'),
      p('Gland plate — MS / Aluminium, L x W x Thick, Hole Dia'), p('Base frame dimension'),
    ]},
    { id: uid(), title: 'Visual Inspection', enabled: true, params: [
      p('Finishing & Aesthetics'), p('Verification of rating plate'), p('Anti-vibration pad'),
      p('Location of panel power earth bus bar'), p('Location of instrument earth bus bar'),
      p('Location of components as per GA drawing'), p('Check power earth / instrument earth bus bar is tinned'),
      p('Component labels / device tag'), p('CT connection TB as per drawing'),
      p('CT star point earthing (S1/S2) as per drawing'), p('PT secondary star point earthing as per drawing'),
      p('Cross-section of area of CT connection'), p('Cross-section — excitation transformer secondary'),
      p('Cross-section of area of AC control cable'), p('Cross-section of area of DC control cable'),
      p('Cross-section of area of earthing cable'), p('Check analog input/output cables are screened'),
      p('Screened terminal connected to instrument earth bus bar'), p('FRLS cable marking on cables'),
      p('Cable color code AC/DC/CT circuit as per drawing'), p('Illumination lamp in control cubicle'),
      p('MCB rating for control circuit — AC/DC'), p('MCB rating for PT and excitation transformer'),
      p('Check door locking and rubber beading pressing'), p('Panel louvers front and back side door'),
      p('Panel lifting hook arrangement as per drawing'), p('Check door earthing cable connection'),
      p('Check adequate vertical turf for outgoing control circuit'), p('Check power socket suitable for project'),
      p('Panel illumination lamp frequency as per drawing'), p('Check Diode location and heat sink — AVR circuit'),
      p('Excitation Ammeter range'),
    ]},
    { id: uid(), title: 'Bill of Material Check (BOM)', enabled: true, params: [p('Bill of material verification against approved BOM')] },
    { id: uid(), title: 'Routine Tests', enabled: true, params: [
      p('AC incomer circuit'), p('DC distribution circuit'), p('24V DC distribution circuit'),
      p('110V / 220V DC distribution circuit'), p('Thermostat functional test'),
      p('Panel illumination circuit'), p('Field input circuit'),
      p('Pre-start condition / aux start / stop circuit'), p('Operation check in manual / auto mode'),
      p('Solenoid circuit'), p('Timer circuit'), p('Breaker close / open circuit (if applicable)'),
      p('Continuity test between power & instrument earth'),
    ]},
    { id: uid(), title: 'Protection Relays', enabled: true, type: 'relay', subGroups: [
      { id: uid(), label: 'Transformer Protection Relay', enabled: true, params: relayParams('6A') },
      { id: uid(), label: 'Generator Protection Relay', enabled: true, params: relayParams('6B') },
      { id: uid(), label: 'Line Protection Relay', enabled: true, params: relayParams('6C') },
      { id: uid(), label: 'Distance Protection Relay', enabled: true, params: relayParams('6D') },
      { id: uid(), label: 'Line Differential Protection Relay', enabled: true, params: relayParams('6E') },
    ]},
    { id: uid(), title: 'AVR (Automatic Voltage Regulator)', enabled: true, params: [
      p('Make'), p('Model number'), p('Current rating'),
      p('Type of communication port'), p('Auxiliary supply'),
      p('Check required inputs uploaded in AVR'), p('Check field flash level uploaded'),
      p('Check digital input/output enabled in AVR'), p('Check diode monitoring protection enabled'),
      p('Check output DC voltage increase/decrease — auto mode'),
      p('Check output DC voltage increase/decrease — manual mode (FCR)'),
      p('Check auto to manual transfer when fault is created'),
      p('Check increase/decrease value in AVR HMI'), p('Check auto to manual mode change in AVR HMI'),
      p('Check digital input to AVR from auxiliary relay'), p('Check digital output from AVR to auxiliary relay'),
      p('Check diode connection from AVR output terminal'), p('Check field flash diode/resistor connection'),
      p('Check DC output voltage in field flash circuit'),
      p('Check auto to auto transfer — double channel AVR (if applicable)'),
      p('Check PF auto reset in AVR'), p('Gen breaker and excitation OFF interlock'),
      p('Excitation ON interlocks after closing gen breaker and grid breaker'),
      p('PF mode ON when Gen. Breaker and Grid breaker interlock'),
      p('Check AVR body earthing connected to instrument earthing'),
    ]},
    { id: uid(), title: 'Transformer Tap Changer Relay (AVR)', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Check input voltage displayed in relay'), p('Check dead band for raise and lower value'),
      p('Check time delay setting in relay'), p('Check under voltage / over voltage LED indication'),
      p('Check raise/lower pulse from relay'), p('Check tap number provision in relay'),
      p('Check raise/lower pulse in auto/manual mode'), p('Check AVR body earthing'),
    ]},
    { id: uid(), title: 'Temperature Scanner', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('No. of channels as per scheme'), p('Type of communication port'),
      p('Alarm temperature setting as per scheme'), p('Trip temperature setting as per scheme'),
      p('Check alarm output relay when RTD is connected'), p('Check TRIP output relay when RTD is connected'),
      p('Check scanner earthing connected to instrument earthing'),
    ]},
    { id: uid(), title: 'Multidisplay Meter (MDM)', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'), p('Type of communication port'),
      p('Check PT/CT ratio entered in MDM'),
      p('Check V / I / PF / HZ / KW / KVA / KVAR / KWH / KVAH / KVARH'),
      p('Check accuracy class during calibration'),
    ]},
    { id: uid(), title: 'HMI', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'), p('Type of communication port'),
      p('Overview screen development as per type of turbine'),
      p('Check SLD screen development as per approved SLD'),
      p('Check MDM parameters in HMI'), p('Check Generator parameters in HMI'),
      p('Check scanner temperature in HMI'), p('Check AVR excitation voltage/current in HMI'),
      p('Check Digital Input and Digital Output in HMI'),
      p('Check each protection fault triggered displayed in HMI'),
      p('Check KW transducer value displayed in HMI'),
      p('Check analog input parameters in HMI'), p('Check speed value displayed in HMI'),
      p('Check online control mode status in HMI'),
      p('Check DI/DO/AI/AO tagging in HMI as per circuit scheme'),
      p('Check HMI body earthing connected to instrument earthing'),
    ]},
    { id: uid(), title: 'Annunciator', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'), p('Type of communication port'),
      p('Check alarm and trip status'), p('Check tagging in window as per circuit scheme'),
      p('Check DC fail / AC fail hooter function'), p('Check annunciator body earthing'),
    ]},
    { id: uid(), title: 'Intake Water Level Indicator & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'Tail Race Level Indicator & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'Guide Vane Indicator & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'Runner Blade Indicator & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'Speed Indicator / Sensor & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect speed sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'PLC (Operational Check)', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply — DC-24V'), p('Firmware version'),
      p('Check number of digital input/output as per scheme'),
      p('Check number of analog input/output as per scheme'),
      p('Check number of RTD input as per scheme'),
      p('Check no. of extension power module — DI/DO/AI/AO/RTD'),
      p('Check digital input in PLC by forcing from auxiliary relay'),
      p('Check digital output card and auxiliary relay function via SCADA/PLC'),
      p('Check analog input card — connecting sensor/external input (4-20 mA)'),
      p('Check analog output card — measure current output (4-20 mA)'),
      p('Check RTD card — connect RTD sensor and measure temperature'),
      p('Check redundant PLC function (if applicable)'),
    ]},
    { id: uid(), title: 'SCADA', enabled: true, params: [
      p('Make'), p('SCADA version'), p('SCADA license'), p('SCADA serial no.'),
      p('No. of computers as per BOM'), p('Printers as per BOM'), p('Check printer function'),
      p('Communication cable as per BOM'),
      p('Check digital input in SCADA screen'), p('Check digital output in SCADA screen'),
      p('Check analog input in SCADA screen'), p('Check analog output in SCADA screen'),
      p('Check RTD value in SCADA screen'), p('Check plant SLD in SCADA screen'),
      p('Check MDM parameter in SCADA screen'), p('Check AVR parameter in SCADA screen'),
      p('Communication check as per PLC architecture'),
    ]},
    { id: uid(), title: 'DEIF Governor / HMI', enabled: true, params: [
      p('Make'), p('Model number'),
      p('Check digital input in GOVERNOR/HMI screen'), p('Check digital output'),
      p('Check analog input'), p('Check analog output'), p('Check RTD value'),
      p('Check plant SLD in GOVERNOR-HMI screen'), p('Check MDM parameter'),
      p('Check AVR parameter'), p('Check safety chain feedback in GOVERNOR'),
      p('Check watchdog feedback in GOVERNOR'),
    ]},
    { id: uid(), title: 'Auto Synchronizing Relay', enabled: true, params: [
      p('Make'), p('Model number'), p('Input program to relay as per scheme'),
      p('Check raise/lower command — change in frequency'),
      p('Check raise/lower command — change in voltage'),
      p('Check breaker closing command from synch relay'),
      p('Check interlock after closing breaker feedback'),
      p('Check terminal details w.r.t. drawing'),
    ]},
    { id: uid(), title: 'Manual Synchronizing Relay', enabled: true, params: [
      p('Make'), p('Model number'), p('Input program to relay as per scheme'),
      p('Check raise/lower command — change in frequency'),
      p('Check raise/lower command — change in voltage'),
      p('Check breaker closing command from synch relay'),
      p('Check interlock after closing breaker feedback'),
      p('Check terminal details w.r.t. drawing'),
    ]},
    { id: uid(), title: 'Check Synchronizing Relay', enabled: true, params: [
      p('Make'), p('Model number'), p('Check circuit and terminal details'),
    ]},
    { id: uid(), title: 'Packing', enabled: true, params: [
      p('Export packing (sea worthy)'), p('Domestic packing'),
    ]},
  ]
}
