import { uid, createParam } from './helpers'

function p(desc) { return createParam(desc) }

function relayParams(prefix) {
  return [
    p('Make'), p('Model number'), p('Current rating'),
    p('Auxiliary supply — AC / DC-24V / DC-110V / DC-220V'),
    p('Type of communication port — RS485 / MODBUS TCP-IP / OFC / IEC 61850'),
    p('Check model & serial number: display vs barcode label'),
    p('Check required inputs uploaded in relay as per design / technical details'),
    p('Check each protection enabled as per trip logic scheme / IEC curve'),
    p('Functional test of each fault as per trip logic scheme'),
    p('Check assigned output including spare is functioning in relay'),
    p('Measure milliamps output for KW in relay after injecting voltage & current'),
    p('Check digital input logic as per trip logic scheme'),
    p('Check LED assigned as per trip logic scheme'),
    p('Check ANSI code pasted on each LED in relay'),
    p('Review PDF extracted file from relay after each parameter is enabled'),
    p('Check relay body earthing connected to instrument earthing'),
  ]
}

export function buildDefaultSections() {
  return [
    { id: uid(), title: 'Bill of Material Check', enabled: true, params: [p('Bill of Material as per approved Drawing')] },
    { id: uid(), title: 'Dimensional Checks', enabled: true, params: [
      p('Panel overall dimension (L x H x B)'), p('Panel sheet thickness'), p('Paint shade'),
      p('Paint thickness (DFT measurement)'), p('Instrument earth bus bar material — Copper / Aluminium'),
      p('Power earth bus bar material — Copper / Aluminium'), p('Earth bus bar size — Specified & Actual'),
      p('Gland plate — MS / Aluminium, L x W x Thick, Hole Dia'), p('Base frame dimension'),
    ]},
    { id: uid(), title: 'Visual Inspection', enabled: true, params: [
      p('Finishing & Aesthetics'), p('Verification of rating plate'), p('Anti-vibration pad'),
      p('Location of panel power earth bus bar'), p('Location of instrument earth bus bar'),
      p('Location of components as per GA drawing'), p('Check power earth / instrument earth bus bar is tinned'),
      p('Component labels / device tag'), p('CT connection TB as per drawing'),
      p('CT star point earthing (S1/S2) as per drawing'), p('PT secondary star point earthing as per drawing'),
      p('Cross-section of area of CT connection'), p('Cross-section — excitation transformer secondary'),
      p('Cross-section of area of AC control cable'), p('Cross-section of area of DC control cable'),
      p('Cross-section of area of earthing cable'), p('Check analog input/output cables are screened'),
      p('Screened terminal connected to instrument earth bus bar'), p('FRLS cable marking on cables'),
      p('Cable color code AC/DC/CT circuit as per drawing'), p('Illumination lamp in control cubicle'),
      p('MCB rating for control circuit — AC/DC'), p('MCB rating for PT and excitation transformer'),
      p('Check door locking and rubber beading pressing'), p('Panel louvers front and back side door'),
      p('Panel lifting hook arrangement as per drawing'), p('Check door earthing cable connection'),
      p('Check adequate vertical turf for outgoing control circuit'), p('Check power socket suitable for project'),
      p('Panel illumination lamp frequency as per drawing'), p('Check Diode location and heat sink — AVR circuit'),
      p('Excitation Ammeter range'),
    ]},
    { id: uid(), title: 'Bill of Material Check (BOM)', enabled: true, params: [p('Bill of material verification against approved BOM')] },
    { id: uid(), title: 'Routine Tests', enabled: true, params: [
      p('AC incomer circuit'), p('DC distribution circuit'), p('24V DC distribution circuit'),
      p('110V / 220V DC distribution circuit'), p('Thermostat functional test'),
      p('Panel illumination circuit'), p('Field input circuit'),
      p('Pre-start condition / aux start / stop circuit'), p('Operation check in manual / auto mode'),
      p('Solenoid circuit'), p('Timer circuit'), p('Breaker close / open circuit (if applicable)'),
      p('Continuity test between power & instrument earth'),
    ]},
    { id: uid(), title: 'Protection Relays', enabled: true, type: 'relay', subGroups: [
      { id: uid(), label: 'Transformer Protection Relay', enabled: true, params: relayParams('6A') },
      { id: uid(), label: 'Generator Protection Relay', enabled: true, params: relayParams('6B') },
      { id: uid(), label: 'Line Protection Relay', enabled: true, params: relayParams('6C') },
      { id: uid(), label: 'Distance Protection Relay', enabled: true, params: relayParams('6D') },
      { id: uid(), label: 'Line Differential Protection Relay', enabled: true, params: relayParams('6E') },
    ]},
    { id: uid(), title: 'AVR (Automatic Voltage Regulator)', enabled: true, params: [
      p('Make'), p('Model number'), p('Current rating'),
      p('Type of communication port'), p('Auxiliary supply'),
      p('Check required inputs uploaded in AVR'), p('Check field flash level uploaded'),
      p('Check digital input/output enabled in AVR'), p('Check diode monitoring protection enabled'),
      p('Check output DC voltage increase/decrease — auto mode'),
      p('Check output DC voltage increase/decrease — manual mode (FCR)'),
      p('Check auto to manual transfer when fault is created'),
      p('Check increase/decrease value in AVR HMI'), p('Check auto to manual mode change in AVR HMI'),
      p('Check digital input to AVR from auxiliary relay'), p('Check digital output from AVR to auxiliary relay'),
      p('Check diode connection from AVR output terminal'), p('Check field flash diode/resistor connection'),
      p('Check DC output voltage in field flash circuit'),
      p('Check auto to auto transfer — double channel AVR (if applicable)'),
      p('Check PF auto reset in AVR'), p('Gen breaker and excitation OFF interlock'),
      p('Excitation ON interlocks after closing gen breaker and grid breaker'),
      p('PF mode ON when Gen. Breaker and Grid breaker interlock'),
      p('Check AVR body earthing connected to instrument earthing'),
    ]},
    { id: uid(), title: 'Transformer Tap Changer Relay (AVR)', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Check input voltage displayed in relay'), p('Check dead band for raise and lower value'),
      p('Check time delay setting in relay'), p('Check under voltage / over voltage LED indication'),
      p('Check raise/lower pulse from relay'), p('Check tap number provision in relay'),
      p('Check raise/lower pulse in auto/manual mode'), p('Check AVR body earthing'),
    ]},
    { id: uid(), title: 'Temperature Scanner', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('No. of channels as per scheme'), p('Type of communication port'),
      p('Alarm temperature setting as per scheme'), p('Trip temperature setting as per scheme'),
      p('Check alarm output relay when RTD is connected'), p('Check TRIP output relay when RTD is connected'),
      p('Check scanner earthing connected to instrument earthing'),
    ]},
    { id: uid(), title: 'Multidisplay Meter (MDM)', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'), p('Type of communication port'),
      p('Check PT/CT ratio entered in MDM'),
      p('Check V / I / PF / HZ / KW / KVA / KVAR / KWH / KVAH / KVARH'),
      p('Check accuracy class during calibration'),
    ]},
    { id: uid(), title: 'HMI', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'), p('Type of communication port'),
      p('Overview screen development as per type of turbine'),
      p('Check SLD screen development as per approved SLD'),
      p('Check MDM parameters in HMI'), p('Check Generator parameters in HMI'),
      p('Check scanner temperature in HMI'), p('Check AVR excitation voltage/current in HMI'),
      p('Check Digital Input and Digital Output in HMI'),
      p('Check each protection fault triggered displayed in HMI'),
      p('Check KW transducer value displayed in HMI'),
      p('Check analog input parameters in HMI'), p('Check speed value displayed in HMI'),
      p('Check online control mode status in HMI'),
      p('Check DI/DO/AI/AO tagging in HMI as per circuit scheme'),
      p('Check HMI body earthing connected to instrument earthing'),
    ]},
    { id: uid(), title: 'Annunciator', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'), p('Type of communication port'),
      p('Check alarm and trip status'), p('Check tagging in window as per circuit scheme'),
      p('Check DC fail / AC fail hooter function'), p('Check annunciator body earthing'),
    ]},
    { id: uid(), title: 'Intake Water Level Indicator & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'Tail Race Level Indicator & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'Guide Vane Indicator & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'Runner Blade Indicator & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'Speed Indicator / Sensor & Transducer', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply'),
      p('Connect speed sensor and check value displayed'), p('Check input program in the indicator'),
      p('Check input and output ferrule in TB'),
    ]},
    { id: uid(), title: 'PLC (Operational Check)', enabled: true, params: [
      p('Make'), p('Model number'), p('Auxiliary supply — DC-24V'), p('Firmware version'),
      p('Check number of digital input/output as per scheme'),
      p('Check number of analog input/output as per scheme'),
      p('Check number of RTD input as per scheme'),
      p('Check no. of extension power module — DI/DO/AI/AO/RTD'),
      p('Check digital input in PLC by forcing from auxiliary relay'),
      p('Check digital output card and auxiliary relay function via SCADA/PLC'),
      p('Check analog input card — connecting sensor/external input (4-20 mA)'),
      p('Check analog output card — measure current output (4-20 mA)'),
      p('Check RTD card — connect RTD sensor and measure temperature'),
      p('Check redundant PLC function (if applicable)'),
    ]},
    { id: uid(), title: 'SCADA', enabled: true, params: [
      p('Make'), p('SCADA version'), p('SCADA license'), p('SCADA serial no.'),
      p('No. of computers as per BOM'), p('Printers as per BOM'), p('Check printer function'),
      p('Communication cable as per BOM'),
      p('Check digital input in SCADA screen'), p('Check digital output in SCADA screen'),
      p('Check analog input in SCADA screen'), p('Check analog output in SCADA screen'),
      p('Check RTD value in SCADA screen'), p('Check plant SLD in SCADA screen'),
      p('Check MDM parameter in SCADA screen'), p('Check AVR parameter in SCADA screen'),
      p('Communication check as per PLC architecture'),
    ]},
    { id: uid(), title: 'DEIF Governor / HMI', enabled: true, params: [
      p('Make'), p('Model number'),
      p('Check digital input in GOVERNOR/HMI screen'), p('Check digital output'),
      p('Check analog input'), p('Check analog output'), p('Check RTD value'),
      p('Check plant SLD in GOVERNOR-HMI screen'), p('Check MDM parameter'),
      p('Check AVR parameter'), p('Check safety chain feedback in GOVERNOR'),
      p('Check watchdog feedback in GOVERNOR'),
    ]},
    { id: uid(), title: 'Auto Synchronizing Relay', enabled: true, params: [
      p('Make'), p('Model number'), p('Input program to relay as per scheme'),
      p('Check raise/lower command — change in frequency'),
      p('Check raise/lower command — change in voltage'),
      p('Check breaker closing command from synch relay'),
      p('Check interlock after closing breaker feedback'),
      p('Check terminal details w.r.t. drawing'),
    ]},
    { id: uid(), title: 'Manual Synchronizing Relay', enabled: true, params: [
      p('Make'), p('Model number'), p('Input program to relay as per scheme'),
      p('Check raise/lower command — change in frequency'),
      p('Check raise/lower command — change in voltage'),
      p('Check breaker closing command from synch relay'),
      p('Check interlock after closing breaker feedback'),
      p('Check terminal details w.r.t. drawing'),
    ]},
    { id: uid(), title: 'Check Synchronizing Relay', enabled: true, params: [
      p('Make'), p('Model number'), p('Check circuit and terminal details'),
    ]},
    { id: uid(), title: 'Packing', enabled: true, params: [
      p('Export packing (sea worthy)'), p('Domestic packing'),
    ]},
  ]
}

// ─── Panel Testing Checklist (Hydro Power Plant) ─────────────────────────────
export function buildChecklistSections() {
  return [
    { id: uid(), title: 'Pre-Test Preparations', enabled: true, params: [
      p('Check for short-circuits in 3-Phase supply, single-phase supply and 24V DC supply'),
      p('All connections are tight. No loose connections'),
      p('No physical damage to the panel or installed devices'),
      p('All components (PLCs, Relay Devices, MFM, VFDs, terminal blocks, power supplies) installed as per design'),
      p('Any item is missing'),
      p('Labelling of wires, terminals, and devices is proper'),
      p('Grounding / earthing connections are in place'),
      p('Voltage levels (24VDC, 230VAC, 415V, etc.) are tested and found OK'),
    ]},
    { id: uid(), title: 'Power Checks (After Powering Up)', enabled: true, params: [
      p('Power supplies and PLC power up correctly without errors'),
      p('All LED indicators on PLCs, I/O modules, and power supplies functioning normally'),
      p('SCADA workstation / server powers up without errors'),
      p('Relay protection devices power up correctly; no trip or fault indication at startup'),
      p('Multifunction Meters power up; display is active and showing readings'),
    ]},
    { id: uid(), title: 'PLC I/O Testing — Digital Inputs', enabled: true, params: [
      p('Input signal simulations OK (push buttons, proximity sensors, wire looping) — DI signals verified at PLC and GOV'),
      p('Correct LED status received at the PLC by observing module LEDs'),
      p('Emergency stop and trip signals (turbine, generator protection) DI verified at PLC'),
    ]},
    { id: uid(), title: 'PLC I/O Testing — Digital Outputs', enabled: true, params: [
      p('Force-checked all Relays, Contactors, indicator lamps etc. and found OK'),
      p('All outputs correctly wired up to terminal blocks for field wiring; verified by forcing / wire looping'),
      p('Governor and exciter control DO signals verified'),
    ]},
    { id: uid(), title: 'PLC I/O Testing — Analog I/O', enabled: true, params: [
      p('Analog signals (4-20mA, 0-10V) at PLC analog input channels checked using signal generator'),
      p('Accurate readings and responses on PLC or HMI, SCADA confirmed'),
      p('Water level / head transducer analog signal (4-20mA) verified at PLC AI channel'),
      p('Vibration / bearing temperature transmitter analog signals verified'),
    ]},
    { id: uid(), title: 'PLC I/O Testing — Signal Loop & Other Modules', enabled: true, params: [
      p('Continuity and functionality for all field signal loops checked using multimeter or loop tester'),
      p('Test functionality of any other PLC module installed (RTD, Thermocouple, Counter, etc.)'),
    ]},
    { id: uid(), title: 'SCADA System Testing', enabled: true, params: [
      p('SCADA software version verified and matches project specification'),
      p('All SCADA mimics / synoptic screens loaded correctly; no errors or missing links'),
      p('All real-time process values (MW, MVAR, voltage, current, frequency, water level, turbine RPM) displayed correctly'),
      p('SCADA tag database verified against I/O list; all tags correctly mapped'),
      p('Historical data trending for key process parameters verified'),
      p('Alarm annunciation on SCADA verified for process high/low limits and equipment fault conditions'),
      p('Alarm acknowledgement and reset functionality verified'),
      p('SCADA event logging and SOE (Sequence of Events) recording verified'),
      p('Remote Start / Stop command from SCADA to PLC for turbine-generator unit verified'),
      p('Remote setpoint adjustment (power setpoint, voltage setpoint) from SCADA to PLC / AVR verified'),
      p('User access levels and login authentication verified on SCADA'),
      p('SCADA to remote control Centre (SLDC / RLDC) communication verified'),
      p('SCADA report generation (daily energy report, event report) verified'),
      p('SCADA server redundancy / failover tested (if applicable)'),
    ]},
    { id: uid(), title: 'Relay Protection Device Testing', enabled: true, type: 'relay', subGroups: [
      { id: uid(), label: 'Generator Protection Relay', enabled: true, params: [
        p('Over-voltage protection (ANSI 59) setting verified and trip output tested'),
        p('Under-voltage protection (ANSI 27) setting verified and trip output tested'),
        p('Over-frequency protection (ANSI 81O) setting verified and trip output tested'),
        p('Under-frequency protection (ANSI 81U) setting verified and trip output tested'),
        p('Differential protection (ANSI 87G) wiring checked; CT polarity and ratio verified'),
        p('Loss of excitation / under-impedance protection (ANSI 40) setting verified'),
        p('Reverse power protection (ANSI 32) setting verified and trip output tested'),
        p('Earth fault / ground fault protection (ANSI 64, 51N) tested'),
      ]},
      { id: uid(), label: 'Transformer Protection Relay', enabled: true, params: [
        p('Over-current protection (ANSI 51) setting verified; trip output tested'),
        p('Differential protection (ANSI 87T) CT ratios and polarity verified'),
        p('Restricted earth fault (ANSI 64R) wiring and settings verified'),
        p('Buchholz relay and temperature trip wiring verified from relay to panel terminal block'),
      ]},
      { id: uid(), label: 'Feeder / Incomer Protection Relay', enabled: true, params: [
        p('Instantaneous over-current (ANSI 50) and time-delayed over-current (ANSI 51) tested'),
        p('Earth fault protection (ANSI 51N) tested'),
        p('Auto-reclose function (ANSI 79) verified (if applicable)'),
      ]},
    ]},
    { id: uid(), title: 'Relay Communication & Integration', enabled: true, params: [
      p('Relay communication port (IEC 61850, Modbus, DNP3, IEC 60870-5-103) wiring verified'),
      p('Relay data (trip signals, status, measurements) readable on SCADA / substation HMI'),
      p('Time synchronization (IRIG-B or NTP) verified on each relay (if applicable)'),
      p('Trip circuit supervision (ANSI 74) verified; healthy indication confirmed'),
      p('All relay output contacts (trip, alarm, close) verified to correct terminal blocks'),
      p('Confirm make, model, and firmware version of each relay matches approved design'),
      p('Relay setting file / parameter file uploaded and verified against protection coordination study'),
      p('Relay self-test / diagnostic function run; no internal fault reported'),
    ]},
    { id: uid(), title: 'Multifunction Meter (MFM) Testing', enabled: true, params: [
      p('Make, model, and accuracy class of each MFM verified against specification'),
      p('PT ratio, CT ratio, and system frequency programmed correctly in each MFM'),
      p('Phase voltage (V_R, V_Y, V_B) readings verified against reference meter'),
      p('Phase current (I_R, I_Y, I_B) readings verified against clamp meter / reference'),
      p('Active power (kW) reading verified'),
      p('Reactive power (kVAR) reading verified'),
      p('Apparent power (kVA) reading verified'),
      p('Power factor reading verified and sign convention confirmed (leading / lagging)'),
      p('Frequency reading verified against SCADA or reference frequency meter'),
      p('Energy parameters: Import kWh, Export kWh, import kVARh, Export kVARh verified'),
      p('Harmonic measurements (THD-V, THD-I) verified if supported by MFM'),
      p('MFM communication (Modbus RTU / TCP) verified; all registers readable on SCADA / PLC'),
      p('MFM display contrast, backlighting, and keypad navigation verified'),
      p('MFM pulsed output (kWh pulse) wiring to PLC DI verified (if applicable)'),
      p('Demand metering parameters (MD kW, MD kVA) verified on MFM (if applicable)'),
    ]},
    { id: uid(), title: 'VFD and Other Devices Testing', enabled: true, params: [
      p('Check VFD control terminal wiring as per drawings (if installed)'),
      p('Adjust VFD parameters as per customer requirement (if installed)'),
      p('Check wiring of all other automation-related devices in the panel (if installed)'),
      p('Adjust parameters / settings of all other automation devices as per customer requirement'),
    ]},
    { id: uid(), title: 'Communication Checks', enabled: true, params: [
      p('Communication between PLC and HMI / SCADA checked and found OK'),
      p('PLC and relay protection devices communication (IEC 61850 / Modbus) checked and found OK'),
      p('PLC and Multifunction Meters communication (Modbus RTU / TCP) checked and found OK'),
      p('PLC and VFDs / Servo drives / remote I/O communication checked and found OK'),
      p('Network status LEDs and diagnostics showing healthy communication on all nodes'),
      p('SCADA to SLDC / RLDC / grid operator communication verified (if applicable)'),
    ]},
    { id: uid(), title: 'Functional Testing', enabled: true, params: [
      p('Dry-run testing (without load) performed to simulate process sequences'),
      p('Alarms and emergency stop operations validated on SCADA and relay panel'),
      p('Generator protection trip tested end-to-end: relay trip → breaker open → SCADA alarm'),
      p('Auto synchronizing sequence tested (if auto-sync relay installed)'),
      p('Interlocks validated and cross-verified against control philosophy / FDS'),
      p('AVR (Automatic Voltage Regulator) interlocking with excitation panel verified'),
      p('Governor control loop (speed / load) dry-tested from PLC / SCADA'),
    ]},
    { id: uid(), title: 'Final Verification / Documentation', enabled: true, params: [
      p('As-built drawings updated (if any changes were made / identified)'),
      p('All test results and observations recorded'),
      p('Test reports, relay setting sheets, calibration certificates, and updated I/O checklists attached'),
      p('MFM calibration certificate / accuracy verification record attached'),
      p('Panel handed over to Quality Control (QC) with all required documentation'),
    ]},
  ]
}
